srsgnb,artifacts: upload artifacts to windows server

diff --git a/.gitlab/ci-shared/e2e.yml b/.gitlab/ci-shared/e2e.yml
--- a/.gitlab/ci-shared/e2e.yml
+++ b/.gitlab/ci-shared/e2e.yml
@@ -68,7 +68,7 @@ variables:
   variables:
     TRANSFER_METER_FREQUENCY: 5s
     ARTIFACT_COMPRESSION_LEVEL: slowest
-    RUNNER_AFTER_SCRIPT_TIMEOUT: 1m
+    RUNNER_AFTER_SCRIPT_TIMEOUT: 20m
     KUBERNETES_CPU_REQUEST: 1
     KUBERNETES_CPU_LIMIT: 2
     KUBERNETES_MEMORY_REQUEST: 2Gi
@@ -156,6 +156,25 @@ variables:
       }
       print_tree "${SRSRANDIR}/tests/e2e/log/" ""
     - echo -e "\e[0Ksection_end:`date +%s`:e2e_folder_section\r\e[0K"
+    #Artifact transfer
+    - |
+      set -x
+      # Verify if SSH connection is active
+      if ! nc -z -v "$FTP_SERVER_IP" 22 >/dev/null 2>&1; then
+          echo "Error: SSH server ${FTP_SERVER_IP}:22 is not active or is not reachable."
+          exit 1
+      fi
+      # Rute the server
+      artifacts_dir="${SRSRANDIR}/tests/e2e/log"
+      compressed_artifact="artifacts_${CI_JOB_NAME_SLUG}_${CI_JOB_ID}.zip"
+      # Define remote path
+      remote_path="E:/artifacts/"
+      # Compress the artifacts
+      zip -r "${compressed_artifact}" "${artifacts_dir}"
+      # Send the artifacts to the server
+      sshpass -p "${SSH_PASS}" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 22 "${compressed_artifact}" "${SSH_USER}@${FTP_SERVER_IP}:${remote_path}"
+      echo "Artifacts sent to the server"
+      echo "artifacts found at ${remote_path}/${compressed_artifact}"
     - |
       subpath=$(echo "$SRSRANDIR" | sed "s|^$CI_PROJECT_DIR||")
       echo "*******************************************************************************************************************************"
